pipeline:
  # Fetch folders from distributed cache
  sftp_cache_restore:
    image: plugins/sftp-cache
    restore: true
    mount:
      - /drone/.ivy2
      - /drone/.sbt
      - /drone/.git

  tests:
    image: scalaplatform/scala:0.6
    pull: true
    environment:
      - COURSIER_CACHE=/drone/cache/coursier
    commands:
      - git log | head -n 20
      - ./bin/checkCLA.sh
      - ./bin/scalafmt --test
      - /usr/bin/sbt ci

  publish:
    image: olafurpg/scalafix:0.3.0
    commands:
      - ./bin/bintray.sh
    when:
      event: push
      branch: [master]

  notify:
    image: drillster/drone-email
    host: smtp.mailgun.org
    username: noreply@drone.geirsson.com
    password: ${MAILGUN_PASSWORD}
    from: noreply@drone.geirsson.com
    recipients:
      - olafurpg@gmail.com
    when:
      event: push
      branch: [master]
      status: [changed, failure]

  # Save folders in distributed cache
  sftp_cache_rebuild:
    image: plugins/sftp-cache
    rebuild: true
    mount:
      - /drone/.ivy2
      - /drone/.sbt
      - /drone/.git
